name: MNmoney
version: '1.0.1.1'
main: money.mnmoney.MNmoney
api-version: '1.21'
load: STARTUP
authors: [ Gordy ]
description: ระบบเงิน Magnus Network - High Performance Caching + Hybrid Storage (MySQL/JSON)
softdepend: [PlaceholderAPI, Vault]

commands:
  mnc:
    description: ดูยอดเงินในกระเป๋าและแบงก์
    usage: /mnc
  mnp:
    description: โอนเงินให้ผู้เล่น
    usage: /mnp <ผู้เล่น> <จำนวน>
  mndeposit:
    description: ฝากเงินเข้าบัญชีแบงก์
    usage: /mndeposit <จำนวน>
  mnwithdraw:
    description: ถอนเงินจากบัญชีแบงก์
    usage: /mnwithdraw <จำนวน>
  mntop:
    description: ดูอันดับเงินรวม top 10
    usage: /mntop
  givemoney:
    description: ให้เงิน (Admin)
    usage: /givemoney <ผู้เล่น> <จำนวน>
  setmoney:
    description: ตั้งเงิน (Admin)
    usage: /setmoney <ผู้เล่น> <จำนวน>
  takemoney:
    description: ยึดเงิน (Admin)
    usage: /takemoney <ผู้เล่น> <จำนวน>
  mnadmin:
    description: คำสั่งจัดการระบบ (Admin)
    usage: /mnadmin <export>

permissions:
  mnmoney.admin:
    description: สิทธิ์สำหรับผู้ดูแลระบบ
    default: op
  mnmoney.top:
    description: สิทธิ์สำหรับดูอันดับผู้เล่นรวยที่สุด
    default: true
